version: '3.9'
name: nook_api
services:

  db:
    image: postgres:15
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:

    build:
      context: .
      dockerfile: Dockerfile.test

    env_file: .env

    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}

    volumes:
      - .:/api

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: 
