name: Run Unit Test via Pytest

on:
  push: 
    branches: ['main', 'dev', 'ESNOOK-71-Configure-Testing-Database']

  pull_request:
    types: [opened, synchronize, reopened]

env:
  USER_NAME: test_user
  PASSWORD: test_pass
  HOST: localhost
  PORT: 5432
  DATABASE_NAME: test_db

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run tests using tox
        run: poetry run tox -e coverage
